version: '2'
services:
  web:
    build: .
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=www.hackes.se,hackes.se
      - LETSENCRYPT_HOST=www.hackes.se,hackes.se
      - LETSENCRYPT_EMAIL=benjick@dumfan.net
